[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
service-macros = { path = "../service-macros" }
bindings = { path = "../bindings" }


[features]
import = ["bindings/import"]