[package]
name = "host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
hyper = { version = "0.14.20", features = ["full"] }
lazy_static = "1.4.0"
tokio = { version = "1", features = ["full"] }
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime" }
#wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime", features = ["tokio"] }
wit-bindgen-host-wasmtime-rust = {git = "https://github.com/AmitPr/wit-bindgen"}
